Updated scripts for use on Mac

diff --git a/buvms b/buvms
--- a/buvms
+++ b/buvms
@@ -5,6 +5,18 @@ then
    exit 1
 fi
 
+if pgrep  "VMware Fusion" >/dev/null
+then
+   echo "Cannot continue since VMware Fusion is running."
+   exit 1
+fi
+
+rsync -Part ~/"Virtual Machines.localized" ~/localA
+rsync -Part ~/"Virtual Machines.localized" ~/localB
+rsync -Part ~/"Virtual Machines.localized" ~/localC
+rsync -Part ~/"Virtual Machines.localized" ~/fastA
+rsync -Part ~/"Virtual Machines.localized" ~/fastB
+rsync -Part ~/"Virtual Machines.localized" ~/slowC
 rsync -Part ~/Parallels ~/fastA
 rsync -Part ~/Parallels ~/fastB
 rsync -Part ~/Parallels ~/slowC
