Update selete to use sudo vmware-toolbox-cmd disk shrink /

diff --git a/compact b/compact
--- a/compact
+++ b/compact
@@ -1,1 +1,9 @@
-/home/sdasgupta/scripts/compact.sh
+#!/bin/bash
+set -e
+if [ z $1 ]
+then
+    echo "Missing file to compact"
+    exit 1
+fi
+vmware-vdiskmanager -r $1 -t 0 copy.vmdk
+mv copy.vmdk $1
